# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: node
pages:
  stage: build
  script:
  - npm ci
  - npm run build
  - ls -l build
  # gitlab pages will only work from a folder called "public" so we move
  # everything there. We `rm -rf public` first to guarantee that it does not
  # exist (it doesn't exist in the source at the time of writing but if we
  # somehow added one later it would break because `build` would get copied
  # *into* `public`)
  - rm -rf public
  - mv build public
  # see https://webd97.de/post/gitlab-pages-compression/
  - gzip -k -6 $(find public -type f -regex ".*\.\(css\|js\|html\|txt\)")
  artifacts:
    paths:
    - public
  only:
  - main
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
