import KoFi from "$lib/sections/KoFi.svelte";
import Investigator from "$lib/sections/Investigator.svelte";
import GitLab from "$lib/sections/GitLab.svelte";
import GitHub from "$lib/sections/GitHub.svelte";
import Twitter from "$lib/sections/Twitter.svelte";
import Email from "$lib/sections/Email.svelte";
const headline="lumphammer projects";
import About from "$lib/sections/About.svelte";
import Instagram from "$lib/sections/Instagram.svelte";
import Discord from "$lib/sections/Discord.svelte";
